container:
  image: node:latest

task:
  name: Test JavaScript SDK
  skip: "!changesInclude('packages/js-sdk/**/*.ts')"
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  bootstrap_script: ./node_modules/.bin/lerna bootstrap
  test_script: ./node_modules/.bin/lerna run --scope kinvey-js-sdk --stream test

task:
  name: Test React Native SDK
  skip: "!changesInclude('packages/react-native-sdk/**/*.ts')"
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  bootstrap_script: ./node_modules/.bin/lerna bootstrap
  build_script: ./node_modules/.bin/lerna run --scope kinvey-js-sdk --scope kinvey-react-native-sdk --stream build
  test_script: ./node_modules/.bin/lerna run --scope kinvey-react-native-sdk --stream test
