language: node_js
node_js:
  - 'stable'

env:
  secure: HQ8ytPTRHx5gF2+UzAuq94vL3Xu17KPvJrbB87C3qYL1dTyqUYEJz65N53MmO5TtYdA5fp3B+QOb5rm+B3WUTBxuaS7w0rr4YRI7AJxg5qh0thUzx3jTLubYNdZtskAy5V5gN5Kzn+eYGPFxp/Kuntxp3y3HDi8ihc0qMTk5aqBbry5I/iQjXzwDL1xNQFbmEpSSy1vAmYWv4IdaQvVhfreLqKU8tYeWH/zd+2UhGXMG/s6t40KXGIasIwXjiZS0Mux6l/r/lUYpaxLgRbyyodTNFZwMYkzhmUTLBJCpPCMdBxjhcRfyUWmzjSugs1vmNP0fc7kcclXxt6BH0l2rDoH88zJnksvWPyZaYDfYYjRb9fL5n7VKMAwUyY6IVbsL9jEyLAgkCTyucnGDl2ZXHCaucfLBMtSkIAlRncHOZMWOkO+U+aBsWCYS73/QnOXm35e697EpDjcQqjb5c6M+rDhB3XrtLCARVbU8O23iaAgQEEtV6ja+guh0MCMTnX+huJs81Q2Ggr5dfMxXCIx3ad23gwTuGZ6icuhOtwYzy8wZB6xJuqqi2Tl+/pBkUVPT044jZzeXrauZz2gT1i/Cdi1mniYNraXCCsnZDhQqpGCCe2ASNZC1ESPts7XpE0Rfro7ILGxhlOKFCuVWyxlLE/uO+XxSeSci2u9Bk32nNkQ=

script:
  - yarn test
after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: thomas.conner@me.com
  api_key:
    secure: zs64wz+OIVD9gKu2qZ+zjDJZsFqBPAM0umhYxdCXvBPfxPnHiy5CYJJWhzi8E/bY9o5jfPRc04OFWcKRYVI0k65fCImpnuettO/ADXJ1fB/9H7YuKyNz/TwFsehmbRiiyyqRQn4neIrXs0ewxZFoh/4+HBN29PCrTj5s2o5Xt+c+44ijON2hpSFZA8emTLscdL0shuWHOv9PCxbfm6E/eBrC0/NW3pWQDOCDFJX7ZQzYX8M3DmSwKyf1U7XOLlUAwZ0FmmncXHrzDGRL2hypbOLae6sY3b34/cE+zi/CGoot5k4QvTrAQewX6ufwu2iAxSU8Fq4zF0Qb1Ry4T20j2XB9IBzEc79nHJT20naBAtZVJ5eKPCeU1yzoWJbM51lAUm2SGzNU3dQue6P71r/PsKD4oJLT2SdGHi+uq492SWWnBN8EJU0w82q1/UnKpUPMazN+lYGNmxCXeQbm5MLOJ0g783LH2XV6vOaESr97B3tNkE30krrwCH148UVcHkBOhkY5U8vwMp+EKv4IFTGZmoBylUMAHCpr7XrYRubHPseFva+pCTd4BfhhEZx8F1ikzC0rbN4/X0yGOnumKbH5s1QL9iU/AvSksyLLEnTQ5ZlCS1yaB02MBt8jK19VT1WWZc66QGpwDsgOSMyvN6Wyju1zpD1clYEEbqIwZgs9kR0=
  on:
    tags: true
    repo: Kinvey/js-sdk

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    secure: zhQEKSmoMrI5yj180Z8NtAqujmMgRI3TIO/DrnFEDjuXziBanKr2Thnzup0Gmr5vfOA1c3yh/HVs671188UDsE6YSf/r8ephjE+dzlk3iyYE6ViHUHB7ju+DKyGOeNPk8yMFUqDhLhtQ9wA8Bvlzbfn/ZwPk2ArDZgp3ixBEmIzB/gkcq4EC+2ciJbBUh99fOPUYspvAvf4xLlQRPNiuZ/BSCfeASRkvYdUp9kAMZecIt2EfAneTAOyEBKc+8ob24Yu5L8GfSnNa8qeAmzwki6WGaVR7EantJ0SA/dXyISlj08ckW/MEY5hoBhy1x0/gsaPaLNfq/GRz1Zj69Qmqz359tknuRBC4lMmEyutG9SKNBB8OAtNyUUnnNi45P+fyTUP/4l+4tYEN4hj/ncnFKvW5P5ls/LZ84wpjfAiUlkVqSwKXUnzccYDYNBfeVMEpTwoxctBgRp9Akalf3nVYfZHvH+/Sy3VGzDqagF+55+kTgfPmf763lKbOanr2HNzpvIfT21UyZ2EEDAoAkqr65HbA+yYgs/Awni02qzalafmIbP3aF9a3yULftubAvfsKALjrde38iqE5kOvsyiFOjescA7chdpJqudn6sT6SuYHaVoaBzqKX0t2aLWq8a9rMoS1qKW22IQ2CQilAtVG5Nb19mcUSjkisoIYnrCvK700=
